// DO NOT edit this file, edit src/common in the root of this repo instead

import * as path from "path";

export const CACHE_FOLDER = path.resolve(".cache");
export const VIEWER_FOLDER = path.resolve("./ptz-viewer/build");
export const SERVER_PORT = 4001;
export const CONFIG_FILE = path.resolve("config.json");
