// DO NOT edit this file, edit src/common in the root of this repo instead

import { JsonObject } from "./json";

export interface Config extends JsonObject {
  captureDevice: string;
  controlsDevice: string;
  captureEnable: boolean;
  captureName: string;
  captureRateMs: number;
}
